repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.11
        args: [-l 120]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args: [--max-line-length=120]

  - repo: local
    hooks:
      - id: run-pip-compile
        name: Create requirements.txt from pyproject.toml
        entry: bash -c 'command -v uv >/dev/null 2>&1 && uv pip compile pyproject.toml --output-file requirements.txt --no-deps >/dev/null 2>&1 || echo "uv not found, skipping"'
        language: system
        types: [python]
        pass_filenames: false
