name: my_project_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - dvc
  - pip:
      - opencv-python
      - torch
      - torchvision
